In [7]:
import sys
import os
import pandas as pd

dat = []
dat1 = pd.read_csv('dat1.txt')
dat.append(dat1)

dat2 = pd.read_csv('dat2.txt')
dat.append(dat2)

dat3 = pd.read_csv('dat3.txt')
dat.append(dat3)

#pd.concat(dat)
data = pd.concat(dat, ignore_index=True)
data.to_json()

,Document,Criteria,Score,Keyphrase,Frequency,Text score
0,Tweet_3.txt,Text score,0.07692,killing,1,0.02564
1,----,Share of lexicon,0.01523,brother,1,0.02564
2,----,----,----,brother,1,0.02564
3,Tweet_9.txt,Text score,0.08594,fight,1,0.00781
4,----,Share of lexicon,0.04061,fight,1,0.00781
5,----,----,----,paradise,1,0.00781
6,----,----,----,brother,2,0.01562
7,----,----,----,brother,2,0.01562
8,----,----,----,armed,1,0.00781
9,----,----,----,fight,1,0.00781
10,----,----,----,islamic state,1,0.01562
11,Tweet_1.txt,Text score,0.08108,fight,1,0.02703
12,----,Share of lexicon,0.01523,fight,1,0.02703
13,----,----,----,fight,1,0.02703